require("core.config")
require("core.mappings")
require("core.lazy")
require("core.theme")

require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.neotree")
require("plugins.lualine")
require("plugins.comment")
require("plugins.rust")
require("plugins.dap")
