-- Core
require("core.configs")
require("core.mappings")
require("core.plugins")
require("core.colors")

-- Plugins
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.snippets")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.comments")
require("plugins.buffline")
require("plugins.toggleterm")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.whichkey")
require("plugins.dashboard")
require("plugins.neotree")
require("plugins.splits")
require("plugins.todo")
require("plugins.colors-highlight")
require("plugins.hop")
require("plugins.lspsaga")
